---
language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
